version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./project/static:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build:
      context: ./project
      dockerfile: dockerfile.prod
    command: gunicorn configs.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./project/static:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres:
  static: