version: '3.8'

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/home/app/web
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    ports:
      - 5432:5432

volumes:
  postgres: